version: '3'
services:
    app:
        image: laravel/app:8.1
        build:
            context: ./docker/app
            dockerfile: ./docker/app/Dockerfile
        networks:
            - appnet
        volumes:
            - ./application:/var/www/html
        ports:
            - ${APP_PORT:-80}:80
        working_dir: /var/www/html
    redis:
        image: redis:7.0.0-alpine3.16
        networks:
            - appnet
        volumes:
            - cachedata:/data
        ports:
            - ${FORWARD_REDIS_PORT:-6379}:6379
    mysql:
        image: mysql:5.7.32
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        networks:
            - appnet
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - ${FORWARD_DB_PORT:-3306}:3306
networks:
    appnet:
        driver: bridge
volumes:
    dbdata:
        driver: local
    cachedata:
        driver: local