version: '3'
services:
    app:
        image: laravel/app:8.1
        build:
            context: ./docker/app
            dockerfile: ./docker/app/Dockerfile
        networks:
            - appnet
        volumes:
            - ./application:/var/www/html
        ports:
            - 80:80
    redis:
        image: redis:7.0.0-alpine3.16
        networks:
            - appnet
        volumes:
            - cachedata:/data
    mysql:
        image: mysql:5.7.32
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
        networks:
            - appnet
        volumes:
            - dbdata:/var/lib/mysql
networks:
    appnet:
        driver: bridge
volumes:
    dbdata:
        driver: local
    cachedata:
        driver: local